exports.ACTIONS = {
    CREATE_LOGIN: 'CREATE_LOGIN',
    UPDATE_LOGIN: 'UPDATE_LOGIN',
    DELETE_LOGIN: 'DELETE_LOGIN',
    REQUEST_CREATE_LOGIN: 'REQUEST_CREATE_LOGIN',
    REQUEST_UPDATE_LOGIN: 'REQUEST_UPDATE_LOGIN',
    REQUEST_DELETE_LOGIN: 'REQUEST_DELETE_LOGIN',
    APPROVE_LOGIN_CREATE: 'APPROVE_LOGIN_CREATE',
    APPROVE_LOGIN_UPDATE: 'APPROVE_LOGIN_UPDATE',
    APPROVE_LOGIN_DELETE: 'APPROVE_LOGIN_DELETE',
    APPROVE_CHANGE_REQUEST: 'APPROVE_CHANGE_REQUEST',
    REJECT_CHANGE_REQUEST: 'REJECT_CHANGE_REQUEST',
    BULK_CHANGE_REQUEST: 'BULK_CHANGE_REQUEST',
    CREATE_COURSE: 'CREATE_COURSE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    DELETE_COURSE: 'DELETE_COURSE',
    REQUEST_CREATE_COURSE: 'REQUEST_CREATE_COURSE',
    REQUEST_UPDATE_COURSE: 'REQUEST_UPDATE_COURSE',
    REQUEST_DELETE_COURSE: 'REQUEST_DELETE_COURSE',
    APPROVE_COURSE_CREATE: 'APPROVE_COURSE_CREATE',
    APPROVE_COURSE_UPDATE: 'APPROVE_COURSE_UPDATE',
    APPROVE_COURSE_DELETE: 'APPROVE_COURSE_DELETE'
};

exports.STATUS = {
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    PARTIAL_SUCCESS: 'PARTIAL_SUCCESS'
};

exports.ROLES = {
    ADMIN: 'admin',
    STAFF: 'staff'
};

exports.CHANGE_TYPES = {
    CREATE: 'CREATE_LOGIN',
    UPDATE: 'UPDATE_LOGIN',
    DELETE: 'DELETE_LOGIN',
    CREATE_COURSE: 'CREATE_COURSE',
    UPDATE_COURSE: 'UPDATE_COURSE',
    DELETE_COURSE: 'DELETE_COURSE'
};
