exports.ACTIONS = {
    UPDATE_LOGIN: 'UPDATE_LOGIN',
    REQUEST_UPDATE_LOGIN: 'REQUEST_UPDATE_LOGIN',
    APPROVE_LOGIN_CHANGE: 'APPROVE_LOGIN_CHANGE',
    REJECT_LOGIN_CHANGE: 'REJECT_LOGIN_CHANGE'
};

exports.STATUS = {
    SUCCESS: 'SUCCESS',
    FAILURE: 'FAILURE',
    PENDING: 'PENDING',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED'
};

exports.ROLES = {
    ADMIN: 'admin',
    STAFF: 'staff'
};